language: node_js
node_js:
  - lts/*
install:
  - npm run bs 
script:
  - npm run build
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
  target_branch: travis
  local_dir: dist
